name: CICDBeta
on:
  push:
    branches:
      - beta
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1

      - name: Yarn Install
        uses: nuxt/actions-yarn@master
        with:
          args: install

      - name: Lerna Bootstrap
        uses: nuxt/actions-yarn@master
        with:
          args: bootstrap

      - name: Lerna Build
        uses: nuxt/actions-yarn@master
        with:
          args: build

      - name: AWS CDK Deploy
        uses: MikeBild/aws-cdk-js-github-action@1.0.0
        with:
          args: deploy --require-approval never --app packages/infrastructure/app.js "$STACK_NAME-*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          STACK_NAME: ECommerce
          STACK_ENV: BETA
