name: AWS Production Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1

      - name: Yarn Install
        uses: nuxt/actions-yarn@master
        with:
          args: install

      - name: Lerna
        uses: nuxt/actions-yarn@master
        with:
          args: lerna

      - name: AWS CDK Destroy (AppSync Fix)
        uses: MikeBild/aws-cdk-js-github-action@1.0.0
        with:
          args: destroy --force --app packages/infrastructure/deploy-backends.js "$CDK_STACK_NAME-$CDK_STACK_ENV-GraphQL"
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_AWS_REGION: eu-central-1
          CDK_STACK_NAME: ECommerce
          CDK_STACK_ENV: PROD

      - name: AWS CDK Deploy Backends
        uses: MikeBild/aws-cdk-js-github-action@1.0.0
        with:
          args: deploy --require-approval never --app packages/infrastructure/deploy-backends.js "$CDK_STACK_NAME-*"
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_AWS_REGION: eu-central-1
          CDK_STACK_NAME: ECommerce
          CDK_STACK_ENV: PROD

      - name: Build
        uses: nuxt/actions-yarn@master
        with:
          args: build
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_AWS_REGION: eu-central-1
          CDK_STACK_NAME: ECommerce
          CDK_STACK_ENV: PROD

      - name: AWS CDK Deploy Frontends
        uses: MikeBild/aws-cdk-js-github-action@1.0.0
        with:
          args: deploy --require-approval never --app packages/infrastructure/deploy-frontends.js "$CDK_STACK_NAME-*"
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_AWS_REGION: eu-central-1
          CDK_STACK_NAME: ECommerce
          CDK_STACK_ENV: PROD

      - name: Sleep (2mins) for AWS Deployment E2E Test activation
        uses: maddox/actions/sleep@master
        with:
          args: 120

      - name: End-To-End Test Run
        uses: nuxt/actions-yarn@master
        with:
          args: test
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_AWS_REGION: eu-central-1
          CDK_STACK_NAME: ECommerce
          CDK_STACK_ENV: PROD
